func main() void {
    break;
}
################################################################################
# [error-stmt-break-outside-of-loop.test.sunder:2] error: break statement outside of loop
#     break;
#     ^
